[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn serve_production:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PORT = "5001"