# Sealos云平台部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-attribute-extractor
  labels:
    app: product-attribute-extractor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-attribute-extractor
  template:
    metadata:
      labels:
        app: product-attribute-extractor
    spec:
      containers:
      - name: product-attribute-extractor
        image: mercy719/product-attribute-extractor:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5001"
        - name: HOST
          value: "0.0.0.0"
        - name: PYTHONPATH
          value: "/app"
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: deepseek-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: flask-secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai-api-key
          optional: true
        - name: MAX_WORKERS
          value: "5"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
        - name: results-storage
          mountPath: /app/results
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: results-storage
        persistentVolumeClaim:
          claimName: results-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-attribute-extractor-service
spec:
  selector:
    app: product-attribute-extractor
  ports:
  - port: 80
    targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # 注意：这些值需要base64编码
  # deepseek-api-key: <base64-encoded-deepseek-key>
  # flask-secret-key: <base64-encoded-secret>
  # openai-api-key: <base64-encoded-openai-key>